In [1]:
# =====================================================================
# SEL 1: IMPORT LIBRARY DAN LOAD DATA READY-MODELING
# =====================================================================
import os
import pandas as pd
import mlflow
from pycaret.regression import setup, compare_models, pull, set_config, tune_model, evaluate_model

# Menggunakan relative path yang aman karena notebook berada di folder 'notebooks'
file_path = os.path.abspath(os.path.join("..", "data", "processed", "final_dataset.csv"))

if os.path.exists(file_path):
    df = pd.read_csv(file_path)
    print(f"✅ Data berhasil dimuat. Total siap modeling: {len(df)} baris.")
else:
    print(f"❌ File tidak ditemukan di: {file_path}")
    print("Pastikan kamu sudah menjalankan tahap preprocessing.")

display(df.head())

✅ Data berhasil dimuat. Total siap modeling: 13026 baris.

,time,location,wave_height,wind_speed_10m,precipitation,visibility,ocean_current_velocity,sea_surface_temperature,wave_height_lag1,wave_height_lag2,...,precipitation_lag3,visibility_lag1,visibility_lag2,visibility_lag3,ocean_current_velocity_lag1,ocean_current_velocity_lag2,ocean_current_velocity_lag3,sea_surface_temperature_lag1,sea_surface_temperature_lag2,sea_surface_temperature_lag3
0,2026-05-08 03:00:00,Bangkalan,0.2,7.1,0.0,40400.0,1.3,31.0,0.2,0.2,...,0.0,37700.0,37700.0,37700.0,0.9,0.4,0.4,31.1,31.1,31.1
1,2026-05-08 04:00:00,Bangkalan,0.2,5.4,0.0,36980.0,1.5,31.0,0.2,0.2,...,0.0,40400.0,37700.0,37700.0,1.3,0.9,0.4,31.0,31.1,31.1
2,2026-05-08 05:00:00,Bangkalan,0.2,8.5,0.0,34320.0,1.5,31.0,0.2,0.2,...,0.0,36980.0,40400.0,37700.0,1.5,1.3,0.9,31.0,31.0,31.1
3,2026-05-08 06:00:00,Bangkalan,0.2,7.5,0.0,34320.0,1.1,31.0,0.2,0.2,...,0.0,34320.0,36980.0,40400.0,1.5,1.5,1.3,31.0,31.0,31.0
4,2026-05-08 07:00:00,Bangkalan,0.2,4.0,0.0,37660.0,0.7,31.0,0.2,0.2,...,0.0,34320.0,34320.0,36980.0,1.1,1.5,1.5,31.0,31.0,31.0

In [2]:
# =====================================================================
# SEL 2: MODELING LOOP & COMPARISON (TOP 3 PER TARGET VARIABLE)
# =====================================================================
# Menyiapkan direktori MLflow
mlflow_tracking_uri = f"file:///{os.path.abspath(os.path.join('..', 'mlruns'))}"
mlflow.set_tracking_uri(mlflow_tracking_uri)
print(f"📁 MLflow Tracking diaktifkan di: {mlflow_tracking_uri}")

# Menghapus fitur identitas agar tidak memicu data leakage
base_df = df.drop(columns=["time", "location", "id_location"], errors='ignore')

all_results = {}
features = [
    "wave_height", "wind_speed_10m", "ocean_current_velocity", 
    "sea_surface_temperature", "precipitation", "visibility"
]

for target in features:
    print(f"\n{'='*20} PROSES SELECTION TARGET: {target.upper()} {'='*20}")
    
    # Pencegahan Data Leakage (Buang target lain)
    other_targets = [col for col in features if col != target]
    target_df = base_df.drop(columns=other_targets, errors='ignore')
    
    # Setup PyCaret
    s = setup(
        data=target_df,
        target=target,
        session_id=123,
        fold=5,
        train_size=0.8,
        verbose=False,
        log_experiment=True, 
        experiment_name=f"Baseline_{target}"
    )
    
    # Mengambil 3 model terbaik berdasarkan RMSE
    best_models = compare_models(n_select=3, sort="RMSE")
    
    # Ekstraksi leaderboard
    results = pull()
    all_results[target] = {"results": results}
    
    print(f"Top 3 Model Terbaik untuk {target}:")
    display(results.head(3)[["Model", "MAE", "RMSE", "R2"]])

# --- KOMPILASI RINGKASAN TOP 3 MODEL ---
compiled_rows = []
for target, data in all_results.items():
    top_3 = data["results"].head(3).copy()
    top_3.insert(0, "Target Variable", target)
    compiled_rows.append(top_3)

pycaret_summary_df = pd.concat(compiled_rows, ignore_index=True)

# Format visualisasi tabel akhir
styled_summary = pycaret_summary_df.style.background_gradient(
    subset=["R2"], cmap="YlGn"
).background_gradient(
    subset=["MAE", "RMSE"], cmap="Reds"
).format({
    "R2": "{:.4f}", "MAE": "{:.4f}", "RMSE": "{:.4f}", "MSE": "{:.4f}", "MAPE": "{:.4f}"
})

print("\n" + "="*50)
print("--- TABEL PERBANDINGAN TOP 3 MODEL PYCARET UNTUK SETIAP TARGET ---")
print("="*50)
display(styled_summary)

# Opsional: Simpan tabel laporan ke CSV untuk presentasi
reports_dir = os.path.abspath(os.path.join("..", "reports"))
os.makedirs(reports_dir, exist_ok=True)
pycaret_summary_df.to_csv(os.path.join(reports_dir, "pycaret_top3_summary.csv"), index=False)

📁 MLflow Tracking diaktifkan di: file:///d:\LENTERA_LAUT\mlruns

==================== PROSES SELECTION TARGET: WAVE_HEIGHT ====================

2026/05/28 09:39:57 INFO mlflow.tracking.fluent: Experiment with name 'Baseline_wave_height' does not exist. Creating a new experiment.

2026/05/28 09:40:26 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:26 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:31 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:31 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:32 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:32 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:33 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:33 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:33 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:34 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:34 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:34 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:35 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:35 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:35 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:35 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:35 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:35 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:36 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:36 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:36 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:36 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:36 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:36 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:37 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:37 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:38 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:40:38 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:40:38 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Top 3 Model Terbaik untuk wave_height:

                                    Model     MAE    RMSE      R2
lr                      Linear Regression  0.0095  0.0136  0.9994
lightgbm  Light Gradient Boosting Machine  0.0099  0.0145  0.9994
xgboost         Extreme Gradient Boosting  0.0103  0.0147  0.9994

==================== PROSES SELECTION TARGET: WIND_SPEED_10M ====================

2026/05/28 09:40:40 INFO mlflow.tracking.fluent: Experiment with name 'Baseline_wind_speed_10m' does not exist. Creating a new experiment.

2026/05/28 09:41:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:33 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:35 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:35 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:39 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:39 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:39 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:39 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:39 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:39 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:40 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:40 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:40 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:40 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:40 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:40 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:41 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:41 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:41 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:41 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:41 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:41 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:42 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:42 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:42 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:43 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:43 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:43 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:43 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:43 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:44 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:44 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:44 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:41:44 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:41:44 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Top 3 Model Terbaik untuk wind_speed_10m:

                                    Model     MAE    RMSE      R2
lightgbm  Light Gradient Boosting Machine  1.5012  2.0063  0.8324
et                  Extra Trees Regressor  1.5019  2.0174  0.8306
rf                Random Forest Regressor  1.5062  2.0236  0.8295

==================== PROSES SELECTION TARGET: OCEAN_CURRENT_VELOCITY ====================

2026/05/28 09:41:46 INFO mlflow.tracking.fluent: Experiment with name 'Baseline_ocean_current_velocity' does not exist. Creating a new experiment.

2026/05/28 09:42:27 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:27 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:29 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:29 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:31 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:31 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:31 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:31 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:32 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:32 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:32 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:32 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:33 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:33 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:34 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:34 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:35 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:35 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:35 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:35 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:36 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:36 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:36 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:36 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:36 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:36 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:37 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:37 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:38 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:38 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:42:38 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:42:38 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Top 3 Model Terbaik untuk ocean_current_velocity:

                                    Model     MAE    RMSE      R2
et                  Extra Trees Regressor  0.0918  0.1538  0.9848
lightgbm  Light Gradient Boosting Machine  0.1002  0.1692  0.9816
xgboost         Extreme Gradient Boosting  0.1026  0.1721  0.9810

==================== PROSES SELECTION TARGET: SEA_SURFACE_TEMPERATURE ====================

2026/05/28 09:42:40 INFO mlflow.tracking.fluent: Experiment with name 'Baseline_sea_surface_temperature' does not exist. Creating a new experiment.

2026/05/28 09:43:08 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:08 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:11 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:11 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:12 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:13 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:13 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:13 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:14 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:14 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:14 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:15 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:15 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:16 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:16 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:16 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:16 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:17 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:17 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:17 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:18 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:18 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:18 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:18 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:18 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:19 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:19 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:19 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:19 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:19 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Top 3 Model Terbaik untuk sea_surface_temperature:

                                    Model     MAE    RMSE      R2
et                  Extra Trees Regressor  0.0366  0.0519  0.9985
rf                Random Forest Regressor  0.0385  0.0527  0.9985
lightgbm  Light Gradient Boosting Machine  0.0392  0.0531  0.9985

==================== PROSES SELECTION TARGET: PRECIPITATION ====================

2026/05/28 09:43:21 INFO mlflow.tracking.fluent: Experiment with name 'Baseline_precipitation' does not exist. Creating a new experiment.

2026/05/28 09:43:51 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:51 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:53 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:53 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:43:59 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:43:59 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:00 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:00 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:00 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:01 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:01 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:01 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:01 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:01 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:02 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:02 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:02 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:02 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:03 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:03 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:03 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:03 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:03 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:04 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:04 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:04 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:04 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:04 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:05 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:05 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:05 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:05 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:06 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:06 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:06 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Top 3 Model Terbaik untuk precipitation:

                                    Model     MAE    RMSE      R2
et                  Extra Trees Regressor  0.0995  0.2875  0.3720
lightgbm  Light Gradient Boosting Machine  0.0991  0.2887  0.3682
gbr           Gradient Boosting Regressor  0.0990  0.2893  0.3656

==================== PROSES SELECTION TARGET: VISIBILITY ====================

2026/05/28 09:44:08 INFO mlflow.tracking.fluent: Experiment with name 'Baseline_visibility' does not exist. Creating a new experiment.

2026/05/28 09:44:51 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:51 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:52 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:52 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:53 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:53 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:54 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:54 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:54 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:54 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:55 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:55 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:55 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:55 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:55 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:55 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:56 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:56 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:56 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:56 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:57 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:57 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:57 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:57 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:58 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:58 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:58 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:58 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:59 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:59 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:59 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:59 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:44:59 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:44:59 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:45:00 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:45:00 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/05/28 09:45:00 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/28 09:45:00 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Top 3 Model Terbaik untuk visibility:

                                    Model        MAE       RMSE      R2
gbr           Gradient Boosting Regressor  4013.1797  6154.1778  0.7609
lightgbm  Light Gradient Boosting Machine  4020.8074  6175.4955  0.7594
ridge                    Ridge Regression  3987.8430  6227.0229  0.7553

==================================================
--- TABEL PERBANDINGAN TOP 3 MODEL PYCARET UNTUK SETIAP TARGET ---
==================================================